experimenting-with-transfer.rs
To run you probably will need to have an instance of Iroha online running local, preferably with docker-compose.yml 
/*
Expected output: 
Asset data: Asset { id: time##user@unreasonable, value: Fixed(Fixed(12.34)) }
Asset data: Asset { id: time##user2@unreasonable, value: Fixed(Fixed(12.34)) }
Error: Transaction was rejected

Caused by:
   0: Validation failed
   1: Operation is not permitted: TransferBox { source_id: AssetId(time##user@unreasonable), object: 1.0_fx, destination_id: AssetId(time##user2@unreasonable) }: Unsupported operation

Location:
    /rustc/f7ca9df69549470541fbf542f87a03eb9ed024b6/library/core/src/convert/mod.rs:716:9


*/

Signed-off-by: Miguel Lemos <miguellemos95@gmail.com>